Server Access Integration
gravitational/predicate-lang pull request #24
Opened 2022-11-01 20:37 UTC by xacrimon

This PR contains changes and primitives needed for integration with Server Access.

Changes
- [ ] Update code translation to generate correct calls for xor & friends
- [ ] Add a general `Resource` primitive for describing read/list access to resources.

2022-11-08 16:15 UTC, klizhentas commented on predicate/solver/teleport.py
> +    # policies is a list of logins/principals assigned to the user
`ssh_logins` is a list of logins/principals (typo)

2022-11-08 22:43 UTC, xacrimon commented on predicate/solver/teleport.py
> +    polices = ast.StringList("user.policies")
They're provided here as a data point to the predicate. They're not for export purposes. My idea for policy_map is to use it to resolve the policies that should apply to a user at the last moment (read: at the point doing the RBAC check). That results in a list of policies we evaluate the predicates of and we can also provide them here.

My reasoning for including this data was to make it easier to work on groups of people within predicates.

2022-11-09 08:40 UTC, vitorenesduarte commented on predicate/solver/teleport.py
> +    polices = ast.StringList("user.policies")
Should we add these 3 when only they're strictly needed?
ATM is not super clear to me if/why they are.

2022-11-09 09:12 UTC, vitorenesduarte commented
Are `where` conditions still supported resource rules?
I noticed them in [RFD 44](https://github.com/gravitational/teleport/blob/master/rfd/0044-session-where-condition.md) but they don't seem to be referenced in [the docs](https://goteleport.com/docs/access-controls/reference/).

2022-11-09 10:51 UTC, xacrimon commented
> the docs

They are indeed supported and an example can be found here https://goteleport.com/docs/access-controls/reference/#rbac-for-sessions

2022-11-09 10:57 UTC, xacrimon commented on predicate/solver/teleport.py
> +    polices = ast.StringList("user.policies")
The main idea was to give all data we have when sensible to increase the flexibility of the system. I don't have any more immediate cases than the one I listed, though. I did end up removing `ssh_logins` as I feel that doesn't mesh too well with the rest of the system.

2022-11-09 10:59 UTC, xacrimon commented on predicate/solver/teleport.py
> +    labels = ast.String("resource.labels")
Including Node doesn't make a lot of sense to me. We don't have data to populate all it's fields at this point. I fixed it and changed it to a stringmap and did some testing.

2022-11-09 10:59 UTC, xacrimon commented on predicate/solver/teleport.py
> +    labels = ast.String("resource.labels")
Keeping it resource-generic makes more sense IMO as it would also apply to things like k8s resources.

2022-11-09 16:15 UTC, vitorenesduarte approved these changes

2022-11-09 16:17 UTC, xacrimon commented
@klizhentas want to give this another look?

2022-11-12 18:20 UTC, klizhentas requested changes

2022-11-12 18:20 UTC, klizhentas commented on predicate/examples/list_nodes.py
> +                (Resource.namespace == "default")
@xacrimon lets remove namespaces for now from Predicate, they are not used, there is only one namespace in all resources today - default one.

2022-11-12 18:20 UTC, klizhentas commented on predicate/solver/teleport.py
> +    polices = ast.StringList("user.policies")
> They're provided here as a data point to the predicate. 

Still, not clear to me what that means, can you elaborate? I understand policy mapping idea that applies when users log in. We can extend policy mapping to apply at different point of interaction between users and resources.

This one is not clear to me, it seems like user is attached policies, how would that interact with policy mapping?

2022-11-13 00:05 UTC, xacrimon commented on predicate/solver/teleport.py
> +    polices = ast.StringList("user.policies")
To figure out what policies we need to check, we run the policy mapping code before evaluating predicates to produce a list of policies to apply. We then provide this list as a predefined variable the predicate can check against if it wants to.

2022-12-04 20:31 UTC, xacrimon commented
@klizhentas Could you please take another look at this when you have a moment to move it forward? Thanks!

2022-12-05 17:07 UTC, klizhentas approved these changes

2022-12-05 17:08 UTC, klizhentas commented
@xacrimon there is one failing test, please fix it and we can merge

2022-12-06 15:17 UTC, merged